spring:
  mail:
    host: smtp.gmail.com
    port: 587
    username: euijae0611@gmail.com
    password: ykzqtysjhfllikkr
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

  datasource:
    url: jdbc:mysql://localhost:3306/board?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: root
    password: P@ssw0rd9495
    driver-class-name: com.mysql.cj.jdbc.Driver