server:
  port: 8090

spring:
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    open-in-view: false
    show-sql: true
    hibernate:
      ddl-auto: update
  thymeleaf:
    cache: false

  h2:
    console:
      enabled: false

  profiles:
    include: info

logging:
  level:
    org.springframework.security: DEBUG


