server:
  port: 8090

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/board?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: root
    password: P@ssw0rd9495
    driver-class-name: com.mysql.cj.jdbc.Driver

logging:
  level:
    org.springframework.security: DEBUG

#  security:
#    user:
#      name: test
#      password: test1234
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    open-in-view: false
    show-sql: true
    hibernate:
      ddl-auto: update
  thymeleaf:
    cache: false
  h2:
    console:
      enabled: false
